export function elementPage(mediaUrl='') {
 const features=[
  ['01','More glass. More possibility.','Slim aluminum profiles','A minimalist frame puts the glass—and the view—at the center of the opening.','Extruded aluminum'],
  ['02','Let the room open outward.','Side-stacking panels','Folding panels stack to the side to connect interior and exterior spaces. Top and bottom rollers support smooth operation.','Top + bottom rollers'],
  ['03','Comfort is in the construction.','Thermal break + insulated glazing','A thermally broken frame helps reduce heat transfer. Double-tempered Low-E glass with argon supports year-round insulation.','Low-E · Argon filled'],
  ['04','Keep the lines clean.','Concealed hardware','Concealed hardware keeps the focus on the door’s slim lines and glass. Handles are included with the door system.','Handles included'],
  ['05','Considered down to the seal.','Drainage, gaskets & seals','Upgraded drainage, gaskets, and rubber strips help resist air and water intrusion at the opening.','Integrated weather sealing'],
  ['06','Close with confidence.','Multi-point locking','The multi-point automatic locking system secures the door at multiple points when closed.','Multi-point automatic']
 ];
 const specs=[['Frame & door','Extruded aluminum'],['Frame construction','Thermally broken'],['Finish','Powder-coated'],['Operation','Folding to exterior'],['Roller system','Top + bottom rollers'],['Glazing','Double-tempered, Low-E, argon filled'],['Thickness','2¾ inches'],['Supply format','Pre-hung'],['Handles','Included'],['Locking','Multi-point automatic'],['Rough opening','At least ½ inch on all sides']];
 return `<link rel="stylesheet" href="/element.css"><script src="/element.js" defer></script>
 <div class="element-subnav"><a href="/series/element/">Element <span>/ Folding doors</span></a><div><a href="#element-features">Explore</a><a href="#element-sizes">Sizes</a><a href="#element-specs">Specifications</a></div></div>
 <section class="element-intro"><div><span class="eyebrow">Element series / Aluminum folding doors</span><h1>Open more<br>of your world.</h1><p>Slim profiles. Expansive glass.<br>A seamless connection between inside and out.</p><a href="#element-features" class="button">Explore the details <span aria-hidden="true">↓</span></a></div><aside><span class="element-symbol">13</span><span>Al</span><small>26.98</small><p>Aluminum.<br>Elemental by design.</p></aside></section>
 <section id="element-features" class="element-story" aria-label="Explore Element folding door features">
  <div class="element-stage"><div class="element-stage-inner"><div class="element-stage-top"><span class="eyebrow">Element / In perspective</span><a href="#element-sizes">Skip to sizes ↓</a></div><div class="element-media"><img src="/assets/element.webp" width="1080" height="1080" alt="Element aluminum folding door shown partially open" class="element-poster">${mediaUrl?`<video id="element-orbit" muted playsinline preload="metadata" poster="/assets/element.webp" aria-label="Illustrative rotating view of the Element folding door"><source src="${mediaUrl}" type="video/mp4"></video>`:''}</div><div class="element-stage-bottom"><span class="mono" id="element-counter" aria-hidden="true">01 / 06</span><span id="element-scroll-hint">Scroll to explore the details</span><button id="element-motion" type="button" aria-pressed="false">Pause rotation</button></div><div class="element-progress" aria-hidden="true"><span></span></div><small class="element-visual-note">Illustrative product view. Configuration shown may vary.</small></div></div>
  <div class="element-chapters">${features.map(([num,title,label,body,tag])=>`<article class="element-chapter" data-chapter="${Number(num)-1}"><span class="eyebrow">${num} / ${label}</span><h2>${title}</h2><p>${body}</p><span class="element-tag mono">${tag}</span></article>`).join('')}</div>
 </section>
 <section class="element-sizes section" id="element-sizes"><div class="section-heading"><div><span class="eyebrow">Fit the opening</span><h2>Your space.<br>Your configuration.</h2></div><p>Stock size options in two heights.<br>Special-order sizes and configurations on request.</p></div><div class="element-size-controls"><label for="element-height">Choose height</label><select id="element-height"><option value="80">80 inches</option><option value="96">96 inches</option></select><span>All dimensions shown in inches.</span></div><div class="element-table-wrap"><table><caption>Element folding door stock size options</caption><thead><tr><th scope="col">Width × height</th><th scope="col">Panels</th><th scope="col">Configurations</th><th scope="col">Operation</th></tr></thead><tbody>${[[72,2,'2L / 2R'],[96,3,'3L / 3R'],[108,3,'3L / 3R'],[120,4,'1L3R / 1R3L'],[144,4,'1L3R / 1R3L']].map(([w,p,c])=>`<tr><th scope="row" class="mono">${w} × <span class="selected-height">80 / 96</span></th><td>${p} panels</td><td class="mono">${c}</td><td>Folding to exterior</td></tr>`).join('')}</tbody></table></div><p class="element-size-note">Stock size listing does not indicate live inventory. Confirm configuration and availability with your dealer before ordering.</p></section>
 <section class="element-specs section" id="element-specs"><div><span class="eyebrow">The details, specified</span><h2>Engineered<br>into every opening.</h2><p>Product specifications for the Element aluminum folding door.</p><a class="button" href="/assets/documents/element-spec-sheet.pdf" target="_blank" rel="noopener">View specification sheet <span aria-hidden="true">↗</span></a><div class="element-finishes"><h3>Available finishes</h3><span><i class="finish-black" aria-hidden="true"></i>Matte black</span><span><i class="finish-white" aria-hidden="true"></i>White</span></div></div><dl>${specs.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl></section>
 <section class="cta"><div><span class="eyebrow">Bring Element to your next project</span><h2>Start with<br>the right opening.</h2></div><a class="button" href="tel:18888213776">Talk to SourcePoint <span aria-hidden="true">↗</span></a></section>`;
}
