import { icon } from './icons.mjs';
import { series } from './catalog.mjs';
import { link, button } from './components.mjs';

const nav = [
  ['/catalog/', 'Collections'],
  ['/company-story/', 'Company'],
  ['/resources/', 'Resources'],
  ['/find-a-dealer/', 'Find a dealer'],
];

export const shell = (title, body, assets = {}) =>
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="SourcePoint supplies premium doors and windows to the trade. Explore six product series and connect with our team."><title>${title} | SourcePoint Doors & Windows</title><link rel="icon" href="/assets/mark.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><script src="/site.js" defer></script>${(assets.styles || []).map((url) => `<link rel="stylesheet" href="${url}">`).join('')}${(assets.scripts || []).map((url) => `<script src="${url}" defer></script>`).join('')}</head><body><a class="skip" href="#main">Skip to content</a><div class="topline"><span>Built for the trade.</span><span>Atlanta, GA Warehouses</span><span class="draft">Website preview</span></div><header><a href="/" aria-label="SourcePoint home"><img class="logo" src="/assets/logo.svg" alt="SourcePoint Doors & Windows" width="220" height="70"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Primary">${nav.map((n) => link(...n)).join('')}${button('/become-a-dealer/', 'Become a dealer')}</nav></header><main id="main">${body}</main><footer><div class="footer-top"><img class="logo" src="/assets/logo-white.svg" alt="SourcePoint Doors & Windows" width="220" height="70"><p>Premium doors & windows.<br>Built for the trade.</p>${link('/contact/', 'Let’s talk ' + icon('right'), 'footer-contact')}</div><div class="footer-grid"><div><span class="eyebrow">Our collections</span>${series.map((s) => link('/series/' + s.id + '/', s.name)).join('')}</div><div><span class="eyebrow">SourcePoint</span>${link('/company-story/', 'Company story')}${link('/executive-bios/', 'Executive bios')}${link('/become-a-dealer/', 'Become a dealer')}${link('/find-a-dealer/', 'Find a dealer')}</div><div><span class="eyebrow">Support</span>${link('/resources/', 'Resources')}${link('/warranty/', 'Warranty & care')}${link('/contact/', 'Contact')}</div><div><span class="eyebrow">Our warehouses</span><p>Atlanta, GA Warehouses</p><p class="muted">Doors and windows for<br>dealers and distributors.</p></div></div><div class="footer-bottom">© 2026 SourcePoint Doors and Windows LLC <span>Built for the trade.</span></div></footer></body></html>`;
